package edu.brown.cs.examples.moshiExample.soup;

import java.util.*;

/**
 * A state container for this demo. In the soup-making story, this class is a pot of soup. The soup
 * may not be entirely finished (indeed, it's often tempting to add more things to a pot of soup).
 * The effects of adding new ingredients to the soup are implemented in the ingredients themselves.
 *
 * <p>For the sake of this demo, we'll keep the soup state relatively simple.
 */
public class Soup {
  /**
   * Internal container for how much of each ingredient the soup contains right now.
   *
   * <p>Note: making the field `final` only keeps us from overwriting the List itself, *not* its
   * contents!
   */
  private final List<String> ingredients = new ArrayList<>();

  private String soupName;

  public Soup(List<String> ingredients) {
    this.ingredients.addAll(ingredients);
  }

  public void stirIn(String ingredient) {
    this.ingredients.add(ingredient);
  }

  /**
   * Find the contents of this pot of soup. The object returned is an unmodifiable view: it will be
   * updated as the pot of soup changes, but doesn't allow modifications.
   *
   * @return an immutable view of the contents of this pot of soup
   */
  public List<String> getIngredients() {
    return Collections.unmodifiableList(this.ingredients);
  }

  public String getSoupName() {
    return this.soupName;
  }

  public void setSoupName(String soupName) {
    this.soupName = soupName;
  }

  //    /**
  //     * Static factory method to make testing easier. Produces a Soup based on parameters and
  // ingredients.
  //     * Does *not* produce ActualFlavorExceptions, even if the chef is timid.
  //     * @param isTimidChef whether the chef is timid
  //     * @param ingredients the set of ingredients to try mixing together
  //     * @return the new Soup object
  //     */
  public static Soup buildNoExceptions(String name, List<String> ingredients) {
    Soup result = new Soup(ingredients);
    result.setSoupName(name);
    //    for(String i: ingredients)
    //        result.stirIn(i);
    return result;
  }

  @Override
  public String toString() {
    return "Soup with " + this.getIngredients().toString();
  }

  /** auto-generated by IntelliJ Code -> generate */
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Soup soup = (Soup) o;
    return Objects.equals(this.ingredients, soup.getIngredients());
  }

  /** auto-generated by IntelliJ Code -> generate */
  @Override
  public int hashCode() {
    return Objects.hash(this.ingredients);
  }
}
